### ISSUE TITLE
Question regarding first-person perspective

### ISSUE THREAD

**Issue by su-narthur** [WillSullivan/idownvotedbecause#23] opened 2017-10-18 12:54 UTC
Looking at [this page](https://github.com/WillSullivan/idownvotedbecause/blob/master/stackoverflow/beingunresponsive.md), I notice you tried out a first-person perspective. Is this something you're interested in continuing to do?

If so, I think this page could be improved by referring to the protagonist in the singular rather than in the plural, to avoid sentences like this, which imply a single question is owned by multiple people:

> There are people trying to help us with our question, but after asking it, we haven't responded to requests for clarification.

I suggest this be reworded this way:

> There are people trying to help me with my question, but after asking it, I haven't responded to requests for clarification.

@WillSullivan Are you open to a pull request that would make this change?

**Comment by WillSullivan** [comment] 2017-10-18 12:59
I was worried it might feel a bit condescending, but having reviewed it for awhile I don't think it comes across that way. I haven't gotten around to rewriting some of the older pages yet, but if you're willing to do so, I'd be willing to pull.

**Comment by su-narthur** [comment] 2017-10-18 13:01
@WillSullivan Ok. So, just clarifying, are you cool with going first-person singular?

**Comment by WillSullivan** [comment] 2017-10-18 17:16
Yup. Let 'er rip.

**Comment by WillSullivan** [comment] 2017-10-19 12:49
Yep, I've definitely mixed them up here, sorry.

**Comment by su-narthur** [comment] 2017-10-19 20:18
@WillSullivan Does that mean you want everything first-person plural? What are your thoughts on cases like this, then, where first-person plural leads to disagreement of number, or the implication of shared ownership?:

> There are people trying to help us with our question, but after asking it, we haven't responded to requests for clarification.

I don't think what this technically says is what's actually intended.

**Comment by WillSullivan** [comment] 2017-10-19 20:31
Eh, this is why I left the note and have pages written in the third person and first person plural (and now in first person... I need to slow down with my responses).  FPP inherently suggests co-ownership, but it's always been that way.

> Are we having fun yet?

Whenever I've been asked that, the person who asked certainly wasn't participating in the activity they were wondering if I was enjoying.  

Certainly, FPS would also suggest ownership.  Not much difference between

> We should return to our question and delete it

versus

> I should return to my question and delete it

Except the first invokes shared learning and the latter rote memorization (_"This is my rifle. There are many like it, but this one is mine."_)

The reason I was toying with FPP was that the third person seems more accusatory ("You should delete your question and improve it") whereas FPP is more of a gentle, schoolmarm-erly approach ("We should delete our question and improve it").  It might be a generational thing, tho.

**Comment by su-narthur** [comment] 2017-10-20 14:13
First-person singular:

> If my question is important enough to ask, it should be important enough for me to check back regularly to respond to anyone commenting on it. If I ignore my question, I'm also ignoring people who are trying to help me. Their time spent analyzing my question, asking for clarification, and waiting for a response is wasted. If they hazard an answer that ends up being incorrect, the time spent on that is wasted. Wasting the time of people who are trying to help me is seen as very rude.

First-person plural:

> If our question is important enough to ask, it should be important enough for us to check back regularly to respond to anyone commenting on it. If we ignore our question, we're also ignoring people who are trying to help us. Their time spent analyzing our question, asking for clarification, and waiting for a response is wasted. If they hazard an answer that ends up being incorrect, the time spent on that is wasted. Wasting the time of people who are trying to help us is seen as very rude.

Second-person:

> If your question is important enough to ask, it should be important enough for you to check back regularly to respond to anyone commenting on it. If you ignore your question, you're also ignoring people who are trying to help you. Their time spent analyzing your question, asking for clarification, and waiting for a response is wasted. If they hazard an answer that ends up being incorrect, the time spent on that is wasted. Wasting the time of people who are trying to help you is seen as very rude.

Third-person:

> If their question is important enough to ask, it should be important enough for them to check back regularly to respond to anyone commenting on it. If they ignore their question, they're also ignoring people who are trying to help them. Their time spent analyzing their question, asking for clarification, and waiting for a response is wasted. If they hazard an answer that ends up being incorrect, the time spent on that is wasted. Wasting the time of people who are trying to help them is seen as very rude.

Reworded to avoid pronouns:

> If a question is important enough to ask, it's important enough for the asker to check back regularly to respond to anyone commenting on it. Ignoring a question means ignoring people who are trying to help. Time spent analyzing the question, asking for clarification, and waiting for a response is wasted. If an answer is hazarded that ends up being incorrect, that time is wasted, too. Wasting the time of people who are trying to help is generally considered quite rude.

First-person plural feels almost patronizing to me, besides my hangups about grammar and technical meaning. First-person singular feels a little presumptuous, forcing the opinion of the writer into the voice of the reader. Second-person sounds quite accusatory, as you already mentioned. Third-person feels like we're talking about someone behind their back. Icky.

I think I prefer the paragraph that's been reworded to avoid pronouns altogether.  What are your thoughts?

**Comment by WillSullivan** [comment] 2017-10-20 16:06
I appreciate the thought and effort you've put into this.  I think you've hit it right on the nose.  Avoiding pronouns seems the best of all options.  Let's make that official.

**Comment by WillSullivan** [comment] 2017-10-20 16:37
Lemme see if this works... merged into #28

**Comment by WillSullivan** [comment] 2017-10-20 16:37
Duplicate of #28

**Comment by WillSullivan** [comment] 2017-10-20 16:37
merge into #28

**Closed** 2017-10-20 16:38 UTC

**Comment by praveenscience** [comment] 2018-03-23 15:49
I may be able to take this up. ☺

**Comment by pinobatch** [comment] 2018-07-22 17:18
The last option still has pronouns, which I have emphasized:
>If a question is important enough to ask, **it**'s important enough for the asker to check back regularly to respond to anyone commenting on **it**.

**Comment by su-narthur** [comment] 2018-07-22 17:36
@pinobatch Good point. The focus of this decision is on pronouns used to refer to the protagonist (the person whose post inspired you to share a link to idownvotedbecause). Pronouns not referring to the protagonist don't seem to cause the problems with tone mentioned above.

What are your thoughts?

**Comment by pinobatch** [comment] 2018-07-22 20:23
Thanks for clarifying.
